### ISSUE TITLE
Error with node bot.js

### ISSUE THREAD

**Issue by Forteewin** [renesansz/discord-greeter-bot#173]
Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Users\Tris2_000\Desktop\Discord Bitch\node_
modules\winston-transport\legacy.js:18:11)
    at DerivedLogger.add (C:\Users\Tris2_000\Desktop\Discord Bitch\node_modules\
winston\lib\winston\logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (C:\Users\Tris2_000\Des
ktop\Discord Bitch\node_modules\winston\lib\winston.js:101:55)
    at Object.<anonymous> (C:\Users\Tris2_000\Desktop\Discord Bitch\bot.js:6:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

**Comment by akshaynexus** [comment]
I get the same error now

**Comment by LeB1610** [comment]
I get the same error

**Comment by ininjapanda** [comment]
I get the same error. Is there any way to fix it?

**Comment by maninuni** [comment]
Change the code:
from
logger.add(logger.transports.Console
logger.add(**new** logger.transports.Console

it should work now

**Comment by RizkyDaulay** [comment]
it still doesnt work.it said
ReferenceError: Discord is not defined
    at Object.<anonymous> (D:\DiscordBot\bot.js:11:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)

@maninuni

**Comment by jahidlebaugh** [comment]
> Change the code:
> from
> logger.add(logger.transports.Console
> logger.add(**new** logger.transports.Console
> 
> it should work now

That helped a TON, thanks man!
